import React from "react";
import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Heading,
  Button,
  Hr,
  Img,
} from "@react-email/components";

interface InsightData {
  title: string;
  summary: string;
  severity: string;
  actionItem: string;
}

interface WeeklyCEOEmailProps {
  companyName: string;
  ceoName: string;
  weekOf: string;
  insights: InsightData[];
  dashboardUrl: string;
}

const severityIcon = (severity: string): string => {
  switch (severity) {
    case "critical":
    case "high":
      return "⚠️";
    case "low":
      return "✅";
    default:
      return "📊";
  }
};

export const WeeklyCEOEmail: React.FC<WeeklyCEOEmailProps> = ({
  companyName,
  ceoName,
  weekOf,
  insights,
  dashboardUrl,
}) => (
  <Html>
    <Head />
    <Body style={{ backgroundColor: "#f6f9fc", fontFamily: "Arial, sans-serif" }}>
      <Container style={{ maxWidth: "600px", margin: "0 auto", padding: "20px" }}>
        {/* Header */}
        <Section
          style={{
            backgroundColor: "#0f172a",
            padding: "24px 32px",
            borderRadius: "8px 8px 0 0",
          }}
        >
          <Text style={{ color: "#d4a853", fontSize: "12px", letterSpacing: "2px", margin: 0 }}>
            PINNACLE EQUITY GROUP
          </Text>
          <Heading style={{ color: "#ffffff", fontSize: "20px", margin: "8px 0 0 0" }}>
            Weekly Performance Update
          </Heading>
        </Section>

        {/* Body */}
        <Section
          style={{
            backgroundColor: "#ffffff",
            padding: "32px",
            borderRadius: "0 0 8px 8px",
          }}
        >
          <Text style={{ fontSize: "14px", color: "#374151" }}>
            Dear {ceoName},
          </Text>
          <Text style={{ fontSize: "14px", color: "#374151" }}>
            Here are the key insights for <strong>{companyName}</strong> for the week of{" "}
            <strong>{weekOf}</strong>:
          </Text>

          {insights.map((insight, idx) => (
            <Section
              key={idx}
              style={{
                backgroundColor: "#f9fafb",
                padding: "16px",
                borderRadius: "6px",
                marginBottom: "12px",
                borderLeft: insight.severity === "critical" ? "4px solid #ef4444" :
                  insight.severity === "high" ? "4px solid #f59e0b" : "4px solid #3b82f6",
              }}
            >
              <Text style={{ fontSize: "15px", fontWeight: "bold", color: "#111827", margin: "0 0 8px 0" }}>
                {severityIcon(insight.severity)} {insight.title}
              </Text>
              <Text style={{ fontSize: "13px", color: "#4b5563", margin: "0 0 8px 0" }}>
                {insight.summary}
              </Text>
              <Text style={{ fontSize: "12px", color: "#6b7280", margin: 0 }}>
                → {insight.actionItem}
              </Text>
            </Section>
          ))}

          <Hr style={{ borderColor: "#e5e7eb", margin: "24px 0" }} />

          <Button
            href={dashboardUrl}
            style={{
              backgroundColor: "#0f172a",
              color: "#ffffff",
              padding: "12px 24px",
              borderRadius: "6px",
              fontSize: "14px",
              textDecoration: "none",
              display: "inline-block",
            }}
          >
            View Full Analysis →
          </Button>
        </Section>

        {/* Footer */}
        <Text style={{ fontSize: "11px", color: "#9ca3af", textAlign: "center" as const, marginTop: "16px" }}>
          Pinnacle Intelligence Platform • Automated Analysis Report
          <br />
          This email was generated by Pinnacle AI. Do not reply directly.
        </Text>
      </Container>
    </Body>
  </Html>
);

export default WeeklyCEOEmail;
